baseURL = 'https://arqueon.github.io/aprendizaje-ia/'
languageCode = 'en-us'
title = 'Aprendizaje Digital e IA'
theme = 'github.com/nunocoracao/blowfish/v2'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
colorScheme = "blowfish"
defaultTheme = "light"
enableSearch = true
showMermaid = true

[params.article]
showMermaid = true

[params.sidebar]
showSidebar = true
groupDepth = 2

[menu]
[[menu.main]]
identifier = "laboratorio"
name = "Laboratorio"
url = "/laboratorio/"
weight = 10
[[menu.main]]
identifier = "observatorio"
name = "Observatorio"
url = "/observatorio/"
weight = 20
[[menu.main]]
identifier = "recursos"
name = "Recursos"
url = "/recursos/"
weight = 30
[[menu.main]]
identifier = "cultura"
name = "Cultura"
url = "/cultura/"
weight = 40
[[menu.main]]
identifier = "marcos-referencia"
name = "Marcos de Referencia"
url = "/marcos-referencia/"
weight = 50

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
